jmx_port: "9999"
jmx_ip: "{{ ec2_private_ip_address }}"

kafka:
  listner_ip: "{{ ec2_private_ip_address }}"
  version_kafka: "0.9.0.1"
  jmx_opts: "-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname={{ jmx_ip }} -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.port={{ jmx_port }} -Dcom.sun.management.jmxremote.rmi.port={{ jmx_port }} -Djava.net.preferIPv4Stack=true "


zookeeper_servers_group: "{{ lookup('env','KAFKA_MANAGER_ZOOKEEPER_SERVERS_GROUP') if lookup('env','KAFKA_MANAGER_ZOOKEEPER_SERVERS_GROUP') != '' else 'standalone_kafka' }}"

kafka_manager:
  installation_type: s3
  sources_tag: 1.3.0.8
  zip_path: bin/kafka-manager-1.3.0.8.zip
  env_vars:
    ZK_HOSTS: "{{ groups['tag_inventory_group_'+zookeeper_servers_group]|map('extract', hostvars, 'ec2_private_ip_address')|list|join(',') }}"
    JMX_PORT: "{{ jmx_port }}"


aws:
  s3:
    bucket: paltalk-kafka-manager
    object: kafka-manager-{{ kafka_manager.sources_tag }}.zip
    download_path: /tmp/kafka-manager.zip