zookeeper_servers_group: "{{ lookup('env','KAFKA_MANAGER_ZOOKEEPER_SERVERS_GROUP') if lookup('env','KAFKA_MANAGER_ZOOKEEPER_SERVERS_GROUP') != '' else 'standalone_kafka' }}"

kafka_manager:
  installation_type: s3
  sources_tag: 1.3.0.8
  zip_path: bin/kafka-manager-1.3.0.8.zip
  env_vars:
    ZK_HOSTS: "{{ groups['tag_inventory_group_'+zookeeper_servers_group]|map('extract', hostvars, 'ec2_private_ip_address')|list|join(',') }}"
    JMX_PORT: "{{ jmx_port }}"